version: '3'

services:
  opendiscuss-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: opendiscuss
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Jakarta"
    ports:
      - "3306:3306"
    volumes:
      - ./migrations/init-table.sql:/docker-entrypoint-initdb.d/1000.sql
