version: "3"

services:
  opendiscuss-mysql:
    image: mysql:8.0
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: opendiscuss
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./migrations/init-table.sql:/docker-entrypoint-initdb.d/1000.sql
      - ./migrations/init-data.sql:/docker-entrypoint-initdb.d/1001.sql

  opendiscuss-go:
    build: .
    network_mode: "host"
    depends_on:
      - opendiscuss-mysql
