// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ITransactionManager is an autogenerated mock type for the ITransactionManager type
type ITransactionManager struct {
	mock.Mock
}

type ITransactionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *ITransactionManager) EXPECT() *ITransactionManager_Expecter {
	return &ITransactionManager_Expecter{mock: &_m.Mock}
}

// WithTransaction provides a mock function with given fields: ctx, fn
func (_m *ITransactionManager) WithTransaction(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ITransactionManager_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type ITransactionManager_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *ITransactionManager_Expecter) WithTransaction(ctx interface{}, fn interface{}) *ITransactionManager_WithTransaction_Call {
	return &ITransactionManager_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *ITransactionManager_WithTransaction_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *ITransactionManager_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *ITransactionManager_WithTransaction_Call) Return(_a0 error) *ITransactionManager_WithTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ITransactionManager_WithTransaction_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *ITransactionManager_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewITransactionManager creates a new instance of ITransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITransactionManager {
	mock := &ITransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
